### Site Settings ###
title               : "Varun's Blog"
description         : Writing on technology, games, and everything in between.
baseurl             : ""
url                 : "https://blog.varunbehera.com"


### Plugins ###
plugins:
  - jekyll-feed
  - jekyll-seo-tag


### Author Info ###
author:
  name              : Varun Behera
  email             : mail@varunbehera.com
  linkedin          : varunbehera
  goodreads         : varunbehera


### Exclude from processing ###
exclude:
  - README.md
  - Gemfile.lock
  - "*.log"
  - jekyll-theme-quartz.gemspec
  - minima.gemspec
  - script/
